### ISSUE TITLE
批量操作报错：AttributeError: 'Namespace' object has no attribute 'input'

### ISSUE THREAD

**Issue by zxjsir-hub** [NotEnding/CoordinateTransform#1]
![图片](https://user-images.githubusercontent.com/78460796/125806595-76290565-0595-4d46-b1b5-b884f62f70e1.png)
你好，经运行批量提示报错，请教下我是什么问题
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\CoordinateTransform-main\coord_converter.py", line 126, in <module>
    if not args.input or not args.output or not args.type:
AttributeError: 'Namespace' object has no attribute 'input'

**Comment by NotEnding** [comment]
> ![图片](https://user-images.githubusercontent.com/78460796/125806595-76290565-0595-4d46-b1b5-b884f62f70e1.png)
> 你好，经运行批量提示报错，请教下我是什么问题
> Traceback (most recent call last):
> File "C:\Users\Administrator\Desktop\CoordinateTransform-main\coord_converter.py", line 126, in
> if not args.input or not args.output or not args.type:
> AttributeError: 'Namespace' object has no attribute 'input'

这个应该是你输入的问题
